### ISSUE TITLE
[Bug/Question]: Does not work when jobs are in the same file?

### ISSUE THREAD

**Issue by jimduchek** [kachick/wait-other-jobs#754]
### What happened?

Stripped down to the following test:
```
name: Testing Wait Other Jobs

on:
    push:
        branches:
            - main
            - staging
            - development
        paths:
            - ".github/workflows/wait_other_job_test.yml"  
    workflow_dispatch:

permissions:
    contents: read # Since v2
    checks: read
    actions: read

jobs:
    job1:
        runs-on: ubuntu-latest

        steps:
            - name: Test 1
              shell: bash
              run: |
                sleep 60

    job2:
        runs-on: ubuntu-latest

        steps:
            - name: Wait
              uses: kachick/wait-other-jobs@v2
```

I expect job2 NOT to finish first.  But it does, the very first poll passes, despite job1 not being done.  If job1 and job2 are in separate yml files, it works as expected.  Behavior is no different if specifying @v1, though THAT does have the interesting log output:

```
Get own job_id
  {
    "ownJobIDs": [
      23740674348,
      23740674474
    ]
  }
```

It seems perhaps it thinks other jobs in the same file are also itself (and therefore shouldn't wait)?

It's actually probably best for me to split my jobs into separate files anyway, but if this is the case (not sure if GH maybe changed something very recently), several of the examples ought not to work either.

### Version

v2.0.4

### Permissions

GITHUB_TOKEN Permissions
  Actions: read
  Checks: read
  Contents: read
  Metadata: read

### Parameters

```
{
    "triggeredCommitSha": "3d0694542d6540fcb92347237727284e13fcafbb",
    "runId": 8657670048,
    "repositoryInfo": {
      "owner": "XXX",
      "repo": "XXX"
    },
    "waitSecondsBeforeFirstPolling": 10,
    "minIntervalSeconds": [15],
    "retryMethod": "equal_intervals",
    "attemptLimits": 1000,
    "isEarlyExit": true,
    "isDryRun": false,
    "waitList": [],
    "skipList": []
  }
```

### Relevant log output

```shell
Not really useful -- it waits 10 seconds, polls, decides to continue:

Wait about 10 seconds before first polling.
Polling 1: 2024-04-12T06:09:52.142Z
  all jobs passed
```
